M48
; DRILL file {KiCad (6.0.4)} date sáb 30 abr 2022 16:21:01
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-30T16:21:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1378
%
G90
G05
T1
X5.3Y-4.1
X5.3Y-4.2
X5.3Y-4.3
T2
X6.0104Y-4.1098
X6.0104Y-4.2
X6.0104Y-4.2902
T3
X5.311Y-3.1
X5.311Y-3.3953
X7.1Y-3.6
X7.1Y-3.8953
T4
X4.5Y-3.111
X4.5Y-3.485
X4.5Y-4.1
X4.5Y-4.474
X7.9Y-3.511
X7.9Y-3.885
T5
X4.3Y-2.6
X4.3Y-5.0
X8.1Y-2.6
X8.1Y-5.0
T0
M30
